plugins {
    id 'java'
    id 'maven-publish'
}

group = 'com.jummania'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}


dependencies {
    implementation project(':processor')
    annotationProcessor project(':processor')
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        register("mavenJava", MavenPublication) {
            from components.java
        }
    }
}