plugins {
    id 'java'
    id 'maven-publish'
}

group = 'com.jummania'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.auto.service:auto-service:1.1.1'
    annotationProcessor 'com.google.auto.service:auto-service:1.1.1'
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        register("mavenJava", MavenPublication) {
            from components.java
        }
    }
}